### ISSUE TITLE
Can not build windows project solution

### ISSUE THREAD

**Issue by tomasgdc** [eegeo/eegeo-example-app#40]
Hi,

I have been trying to build windows solution. But encountered one problem:
I got this error:
![image](https://cloud.githubusercontent.com/assets/10357361/21729863/d574f8e8-d444-11e6-89fe-6fe5c6ab4e62.png)

As far as I was looking at CMakeFile.txt at line 75 
set(cs_project_input_file "${CMAKE_CURRENT_BINARY_DIR}/ExampleAppWPF.csproj.in")

saw that this file had to come from current build folder.
But I had no idea how this file was meant to appear in there. Then I saw this line:
# Create input file based off existing C# project
execute_process(COMMAND cop "${cs_project_file}" ${cs_project_input_file})
execute_process(COMMAND sed -i "s,<ProjectReference.*>,<ProjectReference Include=\"@CMAKE_EXAMPLEAPP_PROJECT_INCLUDE_PATH@\">,g" ${cs_project_input_file})
execute_process(COMMAND cmake -E copy "${cs_project_file}" ${cs_project_input_file})

and as far as I understood it had to copy the file ExampleAppWPF.cspro and edit it. But for some reason the file was not copied. So using some google skills found one solution for this.

Once I changed it to this:
execute_process(COMMAND cmake -E copy "${cs_project_file}" ${cs_project_input_file})

Everything worked fine.
So wanted to ask if you had any problem like this?

I'm using CMAKE 3.6.1

**Comment by vimmy-io** [comment]
Hi Tywyll,

Thanks for raising the issue. We currently only support CMake project creation through the MinGW shell which has all the tools required for various operations during setup.

In your case, CMake forks the process through Windows cmd and is unable to perform Unix related commands which causes cp / sed to fail. This can also be solved by including the correct directory from MinGW in your Path.

Please feel free to let us know if you have any other issues.
