### ISSUE TITLE
Missing Android Studio setup

### ISSUE THREAD

**Issue by ewoks** [eegeo/eegeo-example-app#41]
Google officially doesn't support Eclipse as well as ADT plugin for it for few years already, so it makes sense to change to Android Studio as main IDE if you expect developers to even try this example. Please update project as well as readme to include instructions for Android Studio and remove use of legacy tools.

**Comment by tim-jenks** [comment]
In agreement.

This is on our short-term roadmap so will add this to next release.

**Comment by ianakoto** [comment]
How do you create your own 3D map from a point of interest. Example is creating a 3D map of Togo. There are No 3D maps for a lot of countries in africa.

**Comment by ewoks** [comment]
hi @ian0549 can you please not mix topics and make it more difficult to follow issues? If you think there is need to raise another issue add it, but otherwise please use other ways to communicate with developers

**Comment by tim-jenks** [comment]
Closing as the Android eegeo-example-app now supports Android Studio and the gradle cmake toolchain. Instructions in README.md updated in this commit: https://github.com/eegeo/eegeo-example-app/commit/02e8596e72e5bae281f2d38476d51416e6f9d1cd
