### ISSUE TITLE
Missing so file.

### ISSUE THREAD

**Issue by agcell** [eegeo/eegeo-example-app#42]
couldn't find "libeegeo-mobile-example-app.so"

**Comment by jonty-dawson** [comment]
Hi - could you provide more information about how you are building the app, and any errors from build logs please?

**Comment by agcell** [comment]
03-01 15:04:37.789: E/AndroidRuntime(360): FATAL EXCEPTION: main
03-01 15:04:37.789: E/AndroidRuntime(360): Process: com.eegeo.mobileexampleapp, PID: 360
03-01 15:04:37.789: E/AndroidRuntime(360): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.eegeo.mobileexampleapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.eegeo.mobileexampleapp-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libeegeo-mobile-example-app.so"
03-01 15:04:37.789: E/AndroidRuntime(360): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at java.lang.System.loadLibrary(System.java:1076)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at com.eegeo.mobileexampleapp.BackgroundThreadActivity.<clinit>(BackgroundThreadActivity.java:39)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at java.lang.Class.newInstance(Native Method)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.os.Looper.loop(Looper.java:148)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at java.lang.reflect.Method.invoke(Native Method)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-01 15:04:37.789: E/AndroidRuntime(360): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jonty-dawson** [comment]
Thanks - that looks like an error when running the app on a device, rather than a build log. It's failing to find the shared native lib for the the app, which might be due to the Eclipse project being configured incorrectly.
There are several manual step involved, as described here: 
https://github.com/eegeo/eegeo-example-app/tree/master/android#readme

Could you confirm whether your build succeeded in creating the "libeegeo-mobile-example-app.so" library?

**Comment by tim-jenks** [comment]
Closing as resolved. Please comment and re-open if not resolved. See comment from @jonty-dawson-eegeo above - eclipse setup is tricky and instructions can be found in the readme:

https://github.com/eegeo/eegeo-example-app/tree/master/android#readme

Issue #41 will mitigate this in the medium term with Android Studio support.
