### ISSUE TITLE
VR, AR content creation on eegeo 

### ISSUE THREAD

**Issue by Parveentyagi** [eegeo/eegeo-example-app#43]
Hi,

Please share any demo or procedure to create/add AR, VR content on eegeo 3D map for a particular location/store.

Basically, we want to create AR , VR content by using backend panel and integrated on eegeo map. If, its possible then please share the process with demo.

Thanks and Regards
Parveen

**Comment by tim-jenks** [comment]
Hi,

You can see a cardbord VR demo in this repository: https://github.com/eegeo/cardboard-vr-demo

You can also see an old OS X Oculus VR demo in this repository: https://github.com/eegeo/eegeo-oculus-demo

Hope this helps!

Regards
-Tim
