### ISSUE TITLE
Adding VR AR content on  eegeo map

### ISSUE THREAD

**Issue by Parveentyagi** [eegeo/eegeo-example-app#44]
Hi,

We are looking for AR VR content addition feature on eegeo map.
Does your app provides this.
If yes, then please share the pricing, we want to go ahead with this. 

Regards
Parveen

**Comment by tim-jenks** [comment]
Please see the response to issue #43 - our maps are VR & AR capable and repositories demonstrating the capability are linked in that issue.

Our pricing can be found at http://eegeo.com/pricing/

Alternatively please email enquiries@eegeo.com for direct contact with our business development team!
