### ISSUE TITLE
VR and AR support

### ISSUE THREAD

**Issue by adamsingh1** [eegeo/eegeo-example-app#45]
Hi
I have some requirement like that:
Online shopping and booking the hotel room with Vr experince
3D map view by eegeo i have to create my own icon of VR in eegeo map of Store
When i click on VR icon it in show me actual virtual reality of that store is that possible in eegeo

**Comment by tim-jenks** [comment]
Please see the response to issue #43 - our maps are VR & AR capable and repositories demonstrating the capability are linked in that issue.

Alternatively please email enquiries@eegeo.com for direct contact with our business development team!
