### ISSUE TITLE
ConfigParams.CollisionConfig is not implemented (Unity SDK)

### ISSUE THREAD

**Issue by tonygod** [eegeo/eegeo-example-app#50]
See: https://docs.wrld3d.com/unity/latest/docs/types/Wrld.ConfigParams.CollisionConfig/

ConfigParams is supposed to contain a "Collisions" field (see https://docs.wrld3d.com/unity/latest/docs/types/Wrld.ConfigParams/)

Impact:
Without access to this, it seems to not be possible to set colliders on terrain, roads and buildings.

**Comment by tim-jenks** [comment]
This configuration property will be available next week, non-atomic push of documentation!
