### ISSUE TITLE
Possibility to prevent generating the buildings

### ISSUE THREAD

**Issue by domarchand** [eegeo/eegeo-example-app#53]
Hello! 

In order to make the game lighter on mobile and allow to place some custom objects on the map for gameplay purpose, is there a way to prevent building generations and just keep the grass, roads, water, etc. ? 

I've been disabling the Building gameobject in Unity to and it would look fine, but it's not the optimal thing.  Thanks for any feedback!

**Comment by johnbell84** [comment]
Hello,

Thanks for trying our maps!  Feedback like this is really helpful in guiding which features we should focus on next.

We don't yet have support for disabling the streaming of buildings completely.  In the meantime I'd recommend disabling the root building GameObject, just as you have done.  

We'll be sure to incorporate this into our prioritisation of upcoming tasks.

Best Regards,

John
