### ISSUE TITLE
api token not working

### ISSUE THREAD

**Issue by djcldy** [eegeo/eegeo-example-app#54]

**Comment by djcldy** [comment]
> I am getting the error "refused to set unsafe header content-length chrome"
I am trying to implement this example: https://docs.wrld3d.com/wrld.js/latest/docs/examples/ from my desktop

**Comment by tim-jenks** [comment]
1. Think this is wrld.js issue not wrld-example-app

2. Believe this to be a duplicate of - https://github.com/wrld3d/wrld.js/issues/18 - wrld.js will not work over file:// protocol due to CORS, please run off a loopback server.

Please reopen with more details if I'm misunderstanding !!
