### ISSUE TITLE
RuntimePlatform.OSXDashboardPlayer doesn't exist in Unity 2017.2b

### ISSUE THREAD

**Issue by Chaosknight40k** [eegeo/eegeo-example-app#56]
In CopyPlatformResources.cs, it calls for RuntimePlatform.OSXDashboardPlayer which doesn't exist in unity version 2017.2b and will cause compilation error.

**Comment by marksimpson82** [comment]
Hi,

Thanks for reporting this issue. We've verified that the OSXDashboardPlayer no longer exists in Unity version 2017.2b and have tracked this issue internally. This issue will be fixed when we do our next release on the unity asset store.

Best regards,
-Mark

**Comment by jonty-dawson** [comment]
This now fixed for Wrld Unity SDK 0.5
(internal tracking - MPLY-8709)
