### ISSUE TITLE
Can't move  the camera in GVR Cardboard

### ISSUE THREAD

**Issue by CrazyGhostGame** [eegeo/eegeo-example-app#63]
I use GVR with wrld in Unity.  As we know, Main camera can't move directly in GVR, it needs an empty GameObject as its parent, and then user control the empty GameObject to move the camera.

But when I do this method, the console show "Expected a camera with zero translation (position should be represented in cameraOriginECEF)" , and the wrld can't show complete city in play mode.

Anyone know how to fix it? 
Thanks a lot.

**Comment by tim-jenks** [comment]
Marking invalid as this should be under our unity-api repository here: https://github.com/wrld3d/unity-api/issues

Please see response to https://github.com/wrld3d/unity-api/issues/22
