### ISSUE TITLE
Trees can't be loaded when using a separate camera for streaming map in Unity

### ISSUE THREAD

**Issue by silentsword123** [eegeo/eegeo-example-app#65]
In our Uniyt project, we tried to create a separate camera used for streaming map from WRLD. However, we  found that if we set that camera face to the terrain vertically, trees on the terrain wont't show up.  Does anyone meet same problem before? How could we fix it? Thanks!

**Comment by johnbell84** [comment]
Hi silentsword123,

I suspect the issue you're seeing is to do with the Level of Detail (LOD) that is being selected for display.  To try to maintain good performance, our maps will try to use high-detail geometry in the foreground, but cut down to lower-detail geometry (possibly removing some trees) for objects that are further away.  This is driven from the position of the streaming camera.  I think that if you re-position your streaming camera (the one referenced as "Camera" on your WrldMap instance) to be slightly closer to the area you're focusing on, the trees should re-appear.  You might need to increase the FOV to maintain coverage of an equivalent area.

You can find further discussion of a similar problem here:

    https://github.com/wrld3d/wrld-example-app/issues/59

I hope this helps.  

Kind regards,

John
