### ISSUE TITLE
CMake file issue

### ISSUE THREAD

**Issue by nomantalish** [eegeo/eegeo-example-app#66]
Cause: executing external native build for cmake C:\Users\bpl\AndroidStudioProjects\WorldMap3D\wrld-example-app-master\android\CMakeLists.txt

**Comment by nomantalish** [comment]
Running the wrld example app in Android studio version 3.1.2. When open the project added NDK, CMake and other required libraries. But when build completed showing the above error. No idea what to do now. 
Kindly guide me.

**Comment by jonty-dawson** [comment]
Hi - thanks for question.
We appear to be building without issue, could you attach the full build log with any error messages if you are still having trouble please?
See setup instructions here:
https://github.com/wrld3d/wrld-example-app/tree/master/android#readme

In particular, make sure that you have executed this command from a shell prompt at the root of your local checkout directory - this fetches and installs the WRLD C++ SDK.
```./update.platform.sh -p android```

**Comment by nomantalish** [comment]
Thanks for your response Jonty-Dawson. These are my build log images.
![capture4](https://user-images.githubusercontent.com/26001918/41841056-c1d18a54-7880-11e8-9388-4c42ab50cd83.PNG)
![capture6](https://user-images.githubusercontent.com/26001918/41841064-c5b3328a-7880-11e8-818b-6e322292adff.PNG)
![capture3](https://user-images.githubusercontent.com/26001918/41841065-c5e49e4c-7880-11e8-9816-5007df566a62.PNG)


![capture7](https://user-images.githubusercontent.com/26001918/41841393-9925701a-7881-11e8-96d1-f8fdc488e25a.PNG)

**Comment by jlunderwood** [comment]
Can you check which version of the Android NDK you are using? There is a known issue building wrld-example-app with NDK 17, so if you are using that you could try NDK 16.

If that doesn't work, it looks like there may be more information in C:/Users/bpl/AndroidStudioProjects/WorldMap3D/wrld-example-app-master/android/.externalNativeBuild/cmake/normalRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log .  Could you send that information along?

**Comment by nomantalish** [comment]
I am using NDK 15c someone suggest me who already build this project.

**Comment by jonty-dawson** [comment]
Closing this in sweep.
Build instructions now specify NDK r17c - 
https://github.com/wrld3d/wrld-example-app/tree/master/android#readme
